# Site settings
title: A Song of Ice and Fire
email: game.of.thrones@hbo.com
description: "This is a site for the game of thrones. You can find information about the TV Show from this awesome site."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: gameofthrones
github_username:  gameofthrones

# Build settings
markdown: kramdown
permalink: none
